# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

gems: [jekyll-paginate,jekyll-feed]
paginate: 5
paginate_path: "page:num"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Setup
title:               Lettuce be Cereal
tagline:             'Blog'
description:         'Lettuce be Cereal '
#url:                 "https://joaoeira.github.io"
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              João Eira
  url:               https://twitter.com/joaoeira
  email:             contact@joaoeira.com

# Custom vars
version:             1.0.0

# Archives
jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'




