# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Setup
title:               Lettuce be Cereal
tagline:             ''
description:         'Lettuce be Cereal - Being the blog of João Eira'
url:                 http://joaoeira.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              João Eira
  url:               https://twitter.com/joaoeira
  email:             contact@joaoeira.com

# Custom vars
version:             1.0.0


